name: Test Echo
on:
  workflow_dispatch:
  push: 
    branches: test-workflow

env:
  ENVIRONMENTS: '["dev", "staging", "prod"]'

jobs:
  # define-matrix:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     environments: ${{ steps.environments.outputs.environments }}
  #   steps:
  #     - name: Define Environments
  #       id: environments
  #       run: |
  #         echo 'environments=["dev", "staging", "prod"]' >> "$GITHUB_OUTPUT"

  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.environments.outputs.environments }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Define Environments
        id: environments
        run: |
          ls
          envs=$(cat ./environments.json)
          echo $envs
          echo 'environments=$envs' >> "$GITHUB_OUTPUT"

  echo:
    name: "Run Echo for ${{ matrix.environment }}"
    needs: define-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # environment: ['dev', 'staging', 'prod'] # LIST OF ENVIRONMENTS
        environment: ${{ fromJson(needs.define-matrix.outputs.environments) }}
    steps:
      - run: echo 'hello ${{ matrix.environment }}'
