name: Test Echo
on:
  workflow_dispatch:
  push: 
    branches: test-workflow

env:
  ENVIRONMENTS: 'dev,statging,prod' # list of environments defined once here

jobs:
  echo:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            environment: ['dev', 'staging', 'prod'] # LIST OF ENVIRONMENTS
    steps:
      - run: echo 'hello ${{ matrix.environment }}'
