name: Test Branch Merge w. CRON
on: 
  schedule:
  - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Merge Branches with Git
        run: | 
          git --version
          git config --global user.email "<>"
          git config --global user.name "Github Actions"
          git fetch origin
          git checkout test-workflow
          git merge origin/main --allow-unrelated-histories
          git push origin test-workflow
          git commit -m "[Automated] Merged 'main' into 'test-workflow'"
      
# GH_TOKEN: ${{ secrets.PAT }}
