name: Test Branch Merge w. CRON
on: 
  schedule:
  - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  merge-branch:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # github_token: ${{ secrets.PAT }} # needs a PAT
          source_ref: 'main'
          target_branch: 'test-workflow'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

