name: Test Branch Merge w. CRON
on: 
  schedule:
  - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Merge Branches with Git
        run: | 
          git --version
          git fetch origin
          git checkout prod
          git merge origin/main
          git push origin prod
          git commit -m "[Automated] Merged 'main' into 'prod'"
      
# GH_TOKEN: ${{ secrets.PAT }}
