name: Test CRON
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  job1:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: List files
      run: ls