name: Test Branch Merge w. CRON
on: 
  schedule:
  - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - run: git --version

    # GH_TOKEN: ${{ secrets.PAT }}
